language: elixir

elixir:
  - 1.6.0

addons:
  postgresql: '10.2'

services:
  - postgresql

before_script:
  - cp build/config/travis.exs build/config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
